; --- CONFIGURACIÓN GLOBAL COMPARTIDA ---
[env]
platform = atmelavr
board = uno
framework = arduino
lib_extra_dirs = libraries
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.0.10
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    adafruit/MAX6675 library @ ^1.1.2

; --- ENTORNO 1: Tu software principal (Estación de calor) ---
[env:estacion_principal]
; Compila el comportamiento nativo por defecto (solo lo que está en src)

; --- ENTORNO 2: Tu software de diagnóstico del logic shifter (Carga directa) ---
[env:mantenimiento_hardware_connections_map_TXS0109E]
build_src_filter = -<*> +<../diagnostico/test_connections_map_TXS0108E_ST7735S.cpp>