[platformio]
default_envs = esp32s3

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.0.10
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    adafruit/MAX6675 library @ ^1.1.2
lib_extra_dirs = libraries

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.0.10
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    adafruit/MAX6675 library @ ^1.1.2
lib_extra_dirs = libraries